Introducing UE_IPV4_INTERNET/IMS variable
herlesupreeth/docker_open5gs pull request #181
Opened 2023-06-16 10:43 UTC by b3c3ll

{Added} Introducing UE_IPV4_INTERNET/IMS variable and some minor changes to readme and DOCKER_HOST_IP

This one is for master branch which can be applied to the others!

2023-06-16 11:41 UTC, herlesupreeth commented
Thanks a lot for your effort. Will review over the weekend and merge

2023-06-18 08:38 UTC, b3c3ll commented
Great

2023-06-18 11:09 UTC, herlesupreeth requested changes
Hey thanks again. I left some review comments to be addressed. Once done let me know I will merge it.

2023-06-18 11:09 UTC, herlesupreeth commented on .env
> +UE_IPV4_IMS=192.168.101.0/24
Add a new line here please

2023-06-18 11:09 UTC, herlesupreeth commented on upf/tun_if.py
> +              help='UE IPv4 Address range in CIDR format e.g. {UE_IPV4_INTERNET}')
Dont change here to {UE_IPV4_INTERNET} as 192.168.100.0/24 is meant to be an example for script users

2023-06-18 11:09 UTC, herlesupreeth commented on upf/tun_if.py
> +$ python3 tun_if.py --tun_ifname ogstun --ipv4_range {UE_IPV4_INTERNET} --ipv6_range 2001:230:cafe::/48
Dont change here to {UE_IPV4_INTERNET} as 192.168.100.0/24 is meant to be an example for script users

2023-06-18 11:09 UTC, herlesupreeth commented on upf/upf.yaml
> +      - addr: UE_IPV4_INTERNET
Changing here to UE_IPV4_INTERNET is not enough, you would need to substitute this value using `sed` as seen in upf_init.sh

2023-06-18 11:09 UTC, herlesupreeth commented on upf/upf.yaml
> +      - addr: UE_IPV4_IMS
Changing here to UE_IPV4_IMS is not enough, you would need to substitute this value using `sed` as seen in upf_init.sh

2023-06-18 11:09 UTC, herlesupreeth commented on smf/smf.yaml
> +      - addr: UE_IPV4_INTERNET
Changing here to UE_IPV4_INTERNET is not enough, you would need to substitute this value using sed as seen in smf_init.sh

2023-06-18 11:09 UTC, herlesupreeth commented on smf/smf.yaml
> +      - addr: UE_IPV4_IMS
Changing here to UE_IPV4_IMS is not enough, you would need to substitute this value using sed as seen in smf_init.sh

2023-06-18 11:09 UTC, herlesupreeth commented on .env
> +DOCKER_HOST_IP=$(hostname -I)   # 192.168.1.223
Remove this change please as its better to leave up to users to change to whatever IP they want

2023-06-18 11:09 UTC, herlesupreeth commented on .env
> +SGWU_ADVERTISE_IP=172.22.0.6    # $DOCKER_HOST_IP
Remove this comment as well

2023-06-18 11:09 UTC, herlesupreeth commented on .env
> +UPF_ADVERTISE_IP=172.22.0.8    # $DOCKER_HOST_IP
Remove this comment as well

2023-06-19 15:25 UTC, b3c3ll commented on upf/upf.yaml
> +      - addr: UE_IPV4_INTERNET
As we Exported .env file, there is no need to add "$"  in the .yaml files!
That was ok using docker compose V2.
Anyway, i'll do it!

2023-06-20 05:17 UTC, herlesupreeth approved these changes

2023-06-20 05:17 UTC, merged

2023-06-20 06:56 UTC, b3c3ll commented
would you cherry-pick the commits from master branch to others ( specially hss_cx ) ?
Thanks
Best regards

2023-06-20 07:41 UTC, herlesupreeth commented
Yep, just did that