updated readme
herlesupreeth/docker_open5gs pull request #236
Opened 2023-10-01 20:04 UTC by galalmounir

This PR updates the README file to include more instructions on setting up a cross-network/cross-hosts setup.

This resolves issue #231

2023-10-02 03:37 UTC, s5uishida commented
Hi @galalmounir 

I think docker_open5gs basically describes a configuration where all processes run on one Docker host. I think it supplements the settings for using a real device as eNB or gNB in other cases. docker_open5gs is very useful when considering the configuration with real devices.

If you want to run CN and eNB/gNB with different docker_open5gs, I think you just may configure each one as necessary.

So I think this PR is unnecessary. (It's not complicated.)

Sorry if I misunderstood.

2023-10-03 17:16 UTC, galalmounir commented
I still believe there is value in running the eNB/gNB using docker_open5gs on one machine/network and the CN using docker_open5gs on another machine/network.

docker_open5gs simplifies setup and accelerates testing, especially for research purposes when a real eNB/gNB is unavailable. 

Also, it allows simulating a number of different configurations. My current test scenario is running two eNBs and one CN. All on different machines. This is all using USRP-B210's

I see where you're coming from, however, I still find value in merging the PR to add clarification for such use cases.
We can, however, modify the PR to clarify the different use cases if you prefer (real eNB/gNB vs. SDR-based ones vs. all on one machine)

2023-10-04 00:37 UTC, s5uishida commented
Since docker_open5gs has the following basic configuration examples,

1. all processes run on one Docker host
2. the eNB/gNB and CN which are separated on another machines

I wrote a configuration example based on these for using VoLTE and SMS on the open5gs_hss_cx branch of docker_open5gs as my note.

https://github.com/s5uishida/docker_open5gs_volte_sms_config

Sorry for my example, but I thought it would be a good for each to write their own example as needed.

2023-10-05 11:37 UTC, herlesupreeth commented
Hey, I am on a vacation. Will take a look at this PR once back. Thank you.

2023-10-12 18:52 UTC, herlesupreeth commented on README.md
> +MME_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB is not running the same docker network/host
I dont agree with this change because when a port is published in docker for a service all traffic on that port will be directed to the container IP (MME IP) so there is no need to change the value to DOCKER_HOST_IP

2023-10-12 18:53 UTC, herlesupreeth commented on README.md
> +In addition, replace the following part in the docker compose file (**srsenb.yaml**)
I would probably add a NOTE and state the scenario where this modification is needed.

2023-10-12 18:54 UTC, herlesupreeth requested changes
thanks for the PR, I left few comments to be addressed.

2023-10-17 01:38 UTC, galalmounir commented on README.md
> +MME_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB is not running the same docker network/host
This change is specifically important for the machine running the container for the eNB. The eNB tries to connect/find the MME using this value

2023-10-17 01:38 UTC, galalmounir commented on README.md
> +In addition, replace the following part in the docker compose file (**srsenb.yaml**)
Agreed, I’ll update this part to reflect this

2023-10-17 06:23 UTC, herlesupreeth commented on README.md
> +MME_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB is not running the same docker network/host
Ah, now I see your point. Then I would suggest the following. Make another section below, stating "If eNB/gNB is run in another machine than the machine running EPC/5GC". And, there state this MME_IP change and the changes in srsenb.yaml/srsgnb.yaml.

Sorry for misunderstanding earlier.

2023-10-23 16:58 UTC, galalmounir commented on README.md
> +MME_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB is not running the same docker network/host
No worries! I should've clarified better :)

I've slightly updated the structure of this section to split the two main use cases (same host vs. separate hosts). 

Let me know if the changes make more sense

2023-10-24 06:39 UTC, herlesupreeth commented on README.md
> +MME_IP --> Change this to value of DOCKER_HOST_IP set above only if eNB is not running the same docker network/host
Thanking for making the changes. I will accept the PR.

2023-10-24 06:39 UTC, merged

2023-10-24 07:30 UTC, herlesupreeth commented
I have made additional refactoring of README. Thanks again for the PR.