merging you changes in my kamalio_pcscf.cfg
herlesupreeth/docker_open5gs pull request #348
Opened 2024-08-06 12:20 UTC by NUCLEAR-WAR

I added your changes to this file and test it with my setup.
THE NF Register works perfect.

The NGHTTP2 module needs key and Cert file in pem format to load, I generated a self signed ones, currently replying 204 only on the subscription URI that ends with /terminate.

2024-08-11 06:50 UTC, herlesupreeth commented on pcscf/kamailio_pcscf.cfg
> +##################################################################
please remove this part. I will cherry-pick my commits on top

2024-08-11 06:52 UTC, herlesupreeth commented on pcscf/kamailio_pcscf.cfg
> +modparam("nghttp2", "listen_addr", "172.22.0.21")
i will replace these part later when I cherry-pick my commits on top of your changes

2024-08-11 06:55 UTC, herlesupreeth commented on pcscf/kamailio_pcscf.cfg
> +## 5G N5 Registring PCSCF to SCP   Code added by Supreeth Herle ##
honestly, not a big fan of having my name in the code. So remove it.

2024-08-11 06:56 UTC, herlesupreeth requested changes
There is something strange about this PR. Its missing my changes so I would suggest rebasing the changes in exp_5g_ims_pyhss branch and applying your changes on top

2024-08-11 21:12 UTC, NUCLEAR-WAR commented on pcscf/kamailio_pcscf.cfg
> +modparam("nghttp2", "listen_addr", "172.22.0.21")
that's would be nice

2024-08-12 03:05 UTC, NUCLEAR-WAR commented
can you check it now ?

2024-08-12 06:17 UTC, herlesupreeth commented
Actually we are adding twice (loadmodule "nghttp2" etc) but its okay. Once merged I will fix it. Thanks again.

2024-08-12 06:18 UTC, merged