adding the logic for N5 QoS in register Method
herlesupreeth/docker_open5gs pull request #349
Opened 2024-08-06 12:23 UTC by NUCLEAR-WAR

Here I added the logic for the QoS register only after the IPSec.
used some variable to store some session Information for use later utilizing HTABLE.
Add logic to terminate the session when a de-register comes.

2024-08-11 06:22 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +################################################################################
I would suggest moving all the below logic to a route[] block

2024-08-11 06:27 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +#  jansson_set("array", "codecs", "[\"downlink\\noffer\\n\", \"uplink\\nanswer\\n\"]", "$var(medComp)");
you can remove these commented codes. Also, codecs are not relevant during SIP registration

2024-08-11 06:29 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +  jansson_set("string", "notifUri", "http://172.22.0.21:8284", "$var(payload)");
Try not to hardcode IPs. Once PR is merged I can refactor this part

2024-08-11 06:30 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +  jansson_set("string", "suppFeat", "4", "$var(payload)");
Any reason why its set to 4?

2024-08-11 06:31 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +  jansson_set("array", "fDescs", "[\"permit out ip from $Ri $Rp to $si $sp\", \"permit in ip from $si $sp to $Ri $RAp\"]", "$var(medSubComp)");
shouldn't it be $RAi and $RAp in the flow rules?

2024-08-11 06:32 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    http_client_request_v2pk("POST", "http://172.22.0.27:7777/npcf-policyauthorization/v1/app-sessions", "$var(json_request)", "$var(headers)", "$var(result)" );
same here.. I would suggest reusing the logic I used to substitute with SCP_IP

2024-08-11 06:35 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    xlog("HTTP response: $var(result)\n");
this will log at error level so I would suggest adding correct logging level

2024-08-11 06:40 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    $var(url) = $httprhdr(location);
in order to use the response header dont we need to have the following before `http_client_request_v2pk` ??

`http_client_response_headers_set("1");`

2024-08-11 06:41 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    while ($var(pos) > 0) {
better to use regex here no??

2024-08-11 06:41 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    $var(app_session) = $(var(url){s.substr,$var(start_pos),$var(end_pos)});
you may want to check whether $var(app_session) is empty or null

2024-08-11 06:43 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    if ($expires(min) == 0 || t_check_status("401")) {
why is receiving 401 status considered a de-registration??

2024-08-11 06:44 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    $sht(user_ids=>$var(ue_imsi_reg_ip)) = $var(ue_imsi);
arent you supposed to store the AppSession ID and not IMSI right??

2024-08-11 06:45 UTC, herlesupreeth commented on pcscf/route/register.cfg
> +    http_client_request_v2pk("POST", "http://172.22.0.27:7777/npcf-policyauthorization/v1/app-sessions/$var(user_appsess_dereg)/delete", "$var(json_request)", "$var(headers)", "$var(result)" );
use SCP_IP and try to replace it

2024-08-11 06:46 UTC, herlesupreeth requested changes
thanks for PR..looks great.. I have suggested some changes. Let me know if you need any help

2024-08-12 01:03 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +  jansson_set("string", "suppFeat", "4", "$var(payload)");
not sure why I set it to 4, but I think its should be 2 for "AFsignalFlow" can you confirm it ?

2024-08-12 01:18 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +  jansson_set("array", "fDescs", "[\"permit out ip from $Ri $Rp to $si $sp\", \"permit in ip from $si $sp to $Ri $RAp\"]", "$var(medSubComp)");
changed it, it was the first variable I saw and since then I did not touch it

2024-08-12 01:19 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    xlog("HTTP response: $var(result)\n");
set it to ALERT

2024-08-12 01:24 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    while ($var(pos) > 0) {
feel free to improve it ;) I think that what I was able to do with my little Knowledge.

2024-08-12 01:35 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    if ($expires(min) == 0 || t_check_status("401")) {
It was a left over and also a copy paste the plan was to implement session Termination on the 401 before the IPSec Tunnel has been established, then later changed it to only look for de-reg from some reason I keep the other condition Kamailio is always complaining about it and I promised him always that I will remove it, now its the time ;)

2024-08-12 01:37 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    $sht(user_ids=>$var(ue_imsi_reg_ip)) = $var(ue_imsi);
My plan is to associate every user to its reg_appsession, so in case of two devices there should be two Session for two UE that need to be separably handled and tear-downed

2024-08-12 02:09 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +#  jansson_set("array", "codecs", "[\"downlink\\noffer\\n\", \"uplink\\nanswer\\n\"]", "$var(medComp)");
this is due to a problem called Clipboard ;(

2024-08-12 02:11 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +  jansson_set("string", "notifUri", "http://172.22.0.21:8284", "$var(payload)");
I did that just for quick testing the changes, although I could defined them somewhere.
It would be nice if you improve it.

2024-08-12 02:11 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +  jansson_set("string", "suppFeat", "4", "$var(payload)");
change it to 2

2024-08-12 02:13 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    http_client_request_v2pk("POST", "http://172.22.0.27:7777/npcf-policyauthorization/v1/app-sessions", "$var(json_request)", "$var(headers)", "$var(result)" );
It would be nice if you change it on the final version.

2024-08-12 02:16 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    $sht(user_ids=>$var(ue_imsi_reg_ip)) = $var(ue_imsi);
Still need to check it though, as I still have only one 5G capable device.

2024-08-12 02:17 UTC, NUCLEAR-WAR commented on pcscf/route/register.cfg
> +    http_client_request_v2pk("POST", "http://172.22.0.27:7777/npcf-policyauthorization/v1/app-sessions/$var(user_appsess_dereg)/delete", "$var(json_request)", "$var(headers)", "$var(result)" );
could you do it on the last version ?

2024-08-12 02:19 UTC, NUCLEAR-WAR commented
I hope the new modifications are better now, regarding the hardcoded IPs, I would suggest that you at the end change them to more better way

2024-08-12 06:13 UTC, herlesupreeth approved these changes

2024-08-12 06:14 UTC, merged

2024-08-12 06:14 UTC, herlesupreeth commented
Thanks a lot for your efforts :) Its an awesome contribution you made